### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by mchavezN**

### CODE REVIEW

**Comment by mchavezN** [comment]
@JPLuehrig I know that you just saw what I did, I just wanted to added you never the less

**Comment by mchavezN** [comment]
EP-349

**Review by JPLuehrig — COMMENTED** [review]
Looks good for me

**Review by FPIMKE — APPROVED** [review]

**Review by majidalikhan8baader — APPROVED** [review]
Looks good. Sorry for the delayed review.

**Pull request merged**
